# Generated by Django 4.0.3 on 2022-04-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('hashedPwd', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
                'abstract': False,
            },
        ),
    ]
